In [1]:
%env TF_CPP_MIN_LOG_LEVEL=2

import tensorflow as tf  # noqa: E402

x = tf.Variable([[2.0]])
y = tf.Variable([[-4.0]])

with tf.GradientTape() as t:
    f = (x + y) ** 2 + 2 * x * y

df = t.gradient(f, [x, y])
print(df[0], df[1], sep='\n')


env: TF_CPP_MIN_LOG_LEVEL=2
tf.Tensor([[-12.]], shape=(1, 1), dtype=float32)
tf.Tensor([[0.]], shape=(1, 1), dtype=float32)


In [2]:
print(tf.executing_eagerly())

True


In [9]:
a = tf.constant(1, shape=[1,1])
b = tf.constant([1,2,3,4])
c = tf.constant([[1,2],
                 [3,4],
                 [5,6]], dtype=tf.float16)
print(c)
print(c.numpy())

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [20]:
v1 = tf.Variable([1,2,3,4], dtype=tf.float32)
v1.assign_add([1,1,1,1])

# print(v1)

val_0 = v1[0]
val_12 = v1[1:3]

val_0.assign(10)

print(v1, val_0, val_12, sep='\n')

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([10.,  3.,  4.,  5.], dtype=float32)>
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor([3. 4.], shape=(2,), dtype=float32)


In [22]:
x = tf.constant(range(10)) + 5
x_idx = tf.gather(x, [0, 4])

print(x, x_idx, sep='\n')

tf.Tensor([ 5  6  7  8  9 10 11 12 13 14], shape=(10,), dtype=int32)
tf.Tensor([5 9], shape=(2,), dtype=int32)


In [23]:
v = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
v_idx = v[1, 1]
print(v, v_idx, sep='\n')

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [26]:
a = tf.constant(range(30))
b = tf.reshape(a, (5,6))
c = tf.transpose(b, perm=[1,0])

print(b, c, sep='\n')

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32)
tf.Tensor(
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]], shape=(6, 5), dtype=int32)


In [30]:
x = tf.eye(3)
print(x)
tf.ones([3,3])

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [31]:
tf.random.set_seed(1)
a = tf.random.uniform((3,3))
tf.random.set_seed(1)
b = tf.random.uniform((3,3))
print(a, b, sep='\n')

tf.Tensor(
[[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]], shape=(3, 3), dtype=float32)


In [34]:
a2 = tf.constant(tf.range(1,10), shape=(3,3))
b2 = tf.constant(tf.range(5,14), shape=(3,3))
print(a2, b2, sep='\n')
# tf.matmul(a2, b2)
a2 @ b2


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]], dtype=int32)>

In [37]:
from math import pi
tf.sin(tf.constant([0, 30, 45, 60, 90], dtype=tf.float32) * pi / 180.0)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.        , 0.5       , 0.70710677, 0.86602545, 1.        ],
      dtype=float32)>

In [41]:
x = tf.Variable(2.0)

with tf.GradientTape() as t:
    y = x * x

dy_dx = t.gradient(y, x)
print(dy_dx)

tf.Tensor(4.0, shape=(), dtype=float32)
